micronaut:
  application:
    name: data-upload
  serde:
    enabled: true

aws:
  region: us-east-2
  kinesis:
    stream: sales-stream


logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN
